### PR TITLE
added isUplink property for switch port status

### PR DESCRIPTION
**Pull request by patil-nileshb**
added isUplink property for switch port status per https://developer.cisco.com/meraki/whats-new/#!v1-20-0/whats-updated

### CODE REVIEW

**Review by danielabbatt — APPROVED** [review]

**Comment by danielabbatt** [comment]
Thanks

**Comment by patil-nileshb** [comment]
Thank you @danielabbatt. What's the process to release a nuget pkg minor version ?
I didn't see any github action defined. is it done mannually ?
thanks again.

**Comment by danielabbatt** [comment]
Yes it is manual, but we'll get it up there in the next day or so.

**Comment by danielabbatt** [comment]
1.20.18 has been released now including this change i believe.

**Pull request merged**
